config/routes.rb
Rails.application.routes.draw do
  get 'about_me/biography'

  root 'home#index'

  get '/about_me' => 'about_me#index', as: :about_me

  resources :knowledges

end

app/models/knowledge.rb
class Knowledge < ActiveRecord::Base

  validates_presence_of :noun, :percentage

  scope :of_design, -> { where(type_group: "design").order(percentage: :desc) }
  scope :of_development, -> { where(type_group: "development").order(percentage: :desc) }
  scope :of_data_base, -> { where(type_group: "data_base").order(percentage: :desc) }
  scope :of_documentation, -> { where(type_group: "documentation").order(percentage: :desc) }
  scope :of_operating_systems, -> { where(type_group: "operating_systems").order(percentage: :desc) }
  scope :of_text_editors, -> { where(type_group: "text_editors").order(percentage: :desc) }
  scope :of_other_basic, -> { where(type_group: "other_basic").order(percentage: :desc) }

  def self.search(search)
    if search
      where('noun LIKE ?', "%#{search}%")
    else
      all
    end
  end


end

app/controllers/about_me_controller.rb
class AboutMeController < ApplicationController
  def index
    @design = knowledge.of_design
    @development = knowledge.of_development
    @data_base = knowledge.of_data_base
    @documentation = knowledge.of_documentation
    @operating_systems = knowledge.of_operating_systems
    @text_editors = knowledge.of_text_editors
    @other_basic = knowledge.of_other_basic
  end

  def biography
  end

  def knowledge
  	Knowledge.all
  end

  def abilities
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/knowledges_controller.rb
class KnowledgesController < ApplicationController
  before_action :set_knowledge, only: [:show, :edit, :update, :destroy]

  # GET /knowledges
  # GET /knowledges.json
  def index
    @knowledges = Knowledge.search(params[:search])
    respond_to do |format|
      format.html { render :index}
      format.js
    end
  end

  # GET /knowledges/1
  # GET /knowledges/1.json
  def show
  end

  # GET /knowledges/new
  def new
    @knowledge = Knowledge.new
  end

  # GET /knowledges/1/edit
  def edit
  end

  # POST /knowledges
  # POST /knowledges.json
  def create
    @knowledge = Knowledge.new(knowledge_params)

    respond_to do |format|
      if @knowledge.save
        format.html { redirect_to @knowledge, notice: 'Knowledge was successfully created.' }
        format.json { render :show, status: :created, location: @knowledge }
      else
        format.html { render :new }
        format.json { render json: @knowledge.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /knowledges/1
  # PATCH/PUT /knowledges/1.json
  def update
    respond_to do |format|
      if @knowledge.update(knowledge_params)
        format.html { redirect_to @knowledge, notice: 'Knowledge was successfully updated.' }
        format.json { render :show, status: :ok, location: @knowledge }
      else
        format.html { render :edit }
        format.json { render json: @knowledge.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /knowledges/1
  # DELETE /knowledges/1.json
  def destroy
    @knowledge.destroy
    respond_to do |format|
      format.html { redirect_to knowledges_url, notice: 'Knowledge was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_knowledge
      @knowledge = Knowledge.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def knowledge_params
      params.require(:knowledge).permit(:name, :type, :percentage)
    end
end

app/helpers/about_me_helper.rb
module AboutMeHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/knowledges_helper.rb
module KnowledgesHelper

  def bar_by_color(index, type)
    "bar-#{color_bar(type)}-#{index+1}"
  end

  def color_bar(type)
    case type
    when "Design"
      "green"
    when "Base de Datos"
      "red"
    when "Documentation"
      "orange"
    when "Sistemas Operativos"
      "purple"
    when "Editores de Texto"
      "yellow"
    when "Otros Conocimientos Basicos"
      "pink"
    else
      "blue"
    end
  end

  def porcentage_class_by_range(knowledge)
  	"percentage-#{knowledge.percentage}"
  end

end

app/helpers/navigation_helper.rb
module NavigationHelper
  def active_section(name)
  	puts name
  	puts current_page?(name)
    current_page?(name) ? "active" : ""
  end

end

app/views/about_me/_abilities.slim
span
  =image_tag("icon-check.png", class: "icon-check")
  p Pro-activity, responsibility, dedication, organization, creativity, initiative.

span
  =image_tag("icon-check.png", class: "icon-check")
  p Persevering, enthusiastic, self-taught (Books, Manuals, Internet is my forte to learn).

span
  =image_tag("icon-check.png", class: "icon-check")
  p Logic, algorithmic ability, mathematical reasoning.

span
  =image_tag("icon-check.png", class: "icon-check")
  p Troubleshooting, analytical, troubleshooting.

span
  =image_tag("icon-check.png", class: "icon-check")
  p Adaptable to the environment, group and individual work.

app/views/about_me/_biography.slim
.content-center.col-md-12.section-information
  p Tengo 25 años, vivo en Venezuela, me gradué a los 19 años en TSU en Telecomunicaciones, y para los 23 años de Ingeniería en Informática.

  p Adquirí experiencia en varias empresas dedicadas al desarrollo de software.

  p "Hoy me encuentro trabajando, ofrezco servicios de diseño y desarrollo web o sistemas funcionales para particulares y empresas.

  .last-paragraph
    | Si desea agregar al mundo tecnológico, no busque mas, 
    =link_to "¡contacteme!", "#"
    #contact-me
      .section-phone
        =image_tag("cel.png", class: "icon-contact-me  icon-contact-me-phone with-tooltips")
        .phone-box-tool.box-tool.hidden
          | (0416) 816-76-98

      .section-email
        =image_tag("email.png", class: "icon-contact-me icon-contact-me-email with-tooltips")
        .email-box-tool.box-tool.hidden
          | genesisgonza05@gmail.com

      = link_to 'https://ve.linkedin.com/in/genesis-gonzalez-479814109', :target => "_blank" do
        =image_tag("in.png", class: "icon-contact-me icon-contact-me-linkedin")

.content-center.col-md-12.section-picture
  .col-md-4
    .dialog.hidden-box.col-md-12
      h4 Hay que luchar por lo que queremos y no conformarse con lo que el mundo nos da

    .dialog.dialog-1.col-md-12
      h4 Creo plenamente en las oportunidades que Dios da, y en las bendiciones que nos ofrece cada día

    .dialog.dialog-2.col-md-12
      h4 Soy una persona que generalmente esta segura de las ideas que aporta, y me gusta escuchar la idea de los demás

  .col-md-4
    .dialog.dialog-6.col-md-12
      h4 Hay que luchar por lo que queremos y no conformarse con lo que el mundo nos da

    .image-center.col-md-12
      =image_tag("me.png", class: "picture-me")

    .dialog.dialog-3.col-md-12
      h4 Soy una programadora que se preocupa por su ambiente de trabajo, creo que las buenas ideas vienen en un entorno práctico, cómodo, tranquilo, con opciones para hacerlo más divertido cuando sea necesario

  .col-md-4
    .dialog.hidden-box.col-md-12
      h4 Hay que luchar por lo que queremos y no conformarse con lo que el mundo nos da

    .dialog.dialog-4.col-md-12
      h4 Creo que todos tenemos un potencial extraordinario, solo que muchos no saben cómo usarlo

    .dialog.dialog-5.col-md-12
      h4 Amo lo que hago, y pienso en alternativas para la solucion de problemas, colocando cuidado y compromiso, siendo responsable de mi trabajo

app/views/about_me/_knowledge.slim
.content-left.col-md-6
  = render partial: "about_me/knowledge/bars", locals: { object: @operating_systems, title: "Sistemas Operativos" }

  = render partial: "about_me/knowledge/bars", locals: { object: @development, title: "Development" }

.content-right.col-md-6
  = render partial: "about_me/knowledge/bars", locals: { object: @design, title: "Design" }

  = render partial: "about_me/knowledge/bars", locals: { object: @data_base, title: "Base de Datos" }

  = render partial: "about_me/knowledge/bars", locals: { object: @documentation, title: "Documentation" }

  = render partial: "about_me/knowledge/bars", locals: { object: @text_editors, title: "Editores de Texto" }

  = render partial: "about_me/knowledge/bars", locals: { object: @other_basic, title: "Otros Conocimientos Basicos" }

 

app/views/about_me/index.slim
.home-container#wrap
  .header.nav.navbar.navbar-default role="navigation" 
    = render "shares/header"
  .container#about-me
    .page-header.col-md-12
      .title.pull-left
        h1 Génesis González
      ul.menu-button.pull-right
        li.pull-left
          =link_to "Biografía", "#", class: "active", data: { show: "biography" }
        li.pull-left
          =link_to "Habilidades", "#", data: { show: "abilities" }
        li.pull-left
          =link_to "Conocimientos", "#", data: { show: "knowledge" }

    .page-content.col-md-12
      #biography.content-show.col-md-12
        = render "about_me/biography"

      #abilities.content-show.col-md-12.hidden
        = render "about_me/abilities"

      #knowledge.content-show.col-md-12.hidden
        = render "about_me/knowledge"

#footer
  =render "shares/footer"

script jQuery.noConflict()

app/views/about_me/knowledge/_bars.slim
.knowledge
  h3.title #{title}
  - object.each_with_index do | knowledge, index |
    div id="#{bar_by_color(index, title)}" class="horizontal-bar"
      =knowledge.noun
      div class="percentage-bar pull-right #{porcentage_class_by_range(knowledge)}"
        | #{knowledge.percentage}%

app/views/home/index.slim
nav.navbar.navbar-default.navbar-fixed-top.topnav role="navigation"
  .background-nav
  .container.topnav
    .navbar-header
      button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      a class="navbar-brand topnav" href="/" Home

    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      ul.nav.navbar-nav.navbar-right
        li
          a href="#presentation" Presentation
        li
          a href="#experience" Experience
        li
          a href="#education" Education          
        li
          a href="#contact" Contact

a name="presentation"
.intro-header
  .container
    .row
      .col-lg-12
        .intro-message
          img class="side-image me-image" src="/assets/me-3.png" alt=""
          .section-title-right
            .im-box
              img class="im-image" src="/assets/im-2.png" alt=""
              h1 Génesis Gonzalez
            h2 Y quiero decirte:
            h3 Trata siempre buscar la felicidad, pero..
            h3 No olvides de disfrutar el día de hoy
            hr.intro-divider
            ul.list-inline.intro-social-buttons
              li
                a href="#" class="btn btn-default btn-lg social-icon icon-in"
              li
                a href="#" class="btn btn-default btn-lg social-icon icon-skype"
              li
                a href="#" class="btn btn-default btn-lg social-icon icon-insta"


a name="experience"
#experience-section.content-section-a-one.content-section-a
  .container
    .row
      .col-lg-12.col-sm-12
        hr.section-heading-spacer
        .clearfix
        h2.section-heading
          | EXPERIENCE

        .time-line.col-lg-1.col-sm-1
          span.text Actually
          hr.line-horizontal
          hr.line-vertical
          #circle-1.circle
          #circle-2.circle

        .content.col-lg-11.col-sm-11
          #experience-1.experience
            .row
              .title.col-lg-6.col-sm-5
                span.position Developer RoR
                span.company  – Softwarecriollo
              .location.col-lg-6.col-sm-5
                img class="location-icon" src="/assets/location.png" alt=""
                span.text Miami, FL
            .row
              .time.col-lg-6.col-sm-5
                span.text.date Sep. 2014 – Actually
                span.text.duration (2 years)
              .modality.col-lg-6.col-sm-5
                span.text Modality Remote
            .row
              ul.col-lg-12.list
                li.lead
                  | Actually I’m in the more important project, GreenLight Group, with more than 100 models, is a CRM to a travel agency located in USA. My responsibilities are, implementing the required functionalities by the client and make the code review
                li.lead
                  | I have been leader in 3 projects (Group Signature, Reputation, Kapsulyst), where I planned, coordinated and assigned the weekly tasks, made the code review, and updated production with the team work, and I should support with the development of requirements.
                li.lead
                  | I was developer in projects as LifeQuality, Credentialed Care, Softwarecriollo Blog, where I made some requirements.
                li.lead
                  | TDD practice is applied to all projects, clean code and with the tools as Codeclimate and Shippable integrated into Github or GitLab to keep code quality.
                li.lead
                  | Technologies:
                  .section-tags
                    .box-tag TDD
                    .box-tag Slim
                    .box-tag PostgreSQL
                    .box-tag Ruby on Rails
                    .box-tag Jasmine
                    .box-tag CSS
                    .box-tag Sass
                    .box-tag Less
                    .box-tag Cucumber
                    .box-tag Ubuntu
                    .box-tag Capybara
                    .box-tag Rspec
                    .box-tag CoffeeScript
                    .box-tag MySQL
                    .box-tag ActiveAdmin
                    .box-tag BluePay
                    .box-tag Javascript
                    .box-tag Php
                    .box-tag ReactJs
                    .box-tag HTML

          #experience-2.experience
            .row
              .title.col-lg-6.col-sm-5
                span.position Web Developer
                span.company  – Coral Vision Systems, C.A
              .location.col-lg-6.col-sm-5
                img class="location-icon" src="/assets/location.png" alt=""
                span.text Caracas, VE
            .row
              .time.col-lg-6.col-sm-5
                span.text.date Jul. 2014 - Dec. 2014
                span.text.duration (6 months)
              .modality.col-lg-6.col-sm-5
                span.text Modality Remote
            .row
              ul.col-lg-12.list
                li.lead
                  | I was part of development of the project English For Kids, a system that permit management English classes, my responsibilities were develop the required modifies and the QA of some modules.
                li.lead
                  | Technologies:
                  .section-tags
                    .box-tag Php
                    .box-tag jQuery
                    .box-tag CSS
                    .box-tag Windows XP
                    .box-tag MySQL
                    .box-tag Filezilla
                    .box-tag Javascript
                    .box-tag HTML

          #experience-3.experience
            .row
              .title.col-lg-6.col-sm-5
                span.position Developer RoR
                span.company  – Daniel Zambrano
              .location.col-lg-6.col-sm-5
                img class="location-icon" src="/assets/location.png" alt=""
                span.text Caracas, VE
            .row
              .time.col-lg-6.col-sm-5
                span.text.date Jun. 2014 – Sep. 2014
                span.text.duration (4 months)
              .modality.col-lg-6.col-sm-5
                span.text Modality Remote
            .row
              ul.col-lg-12.list
                li.lead
                  | I worked in projects as Samymotors, Dirección Ejecutiva de la Magistratura de Venezuela and Veneventos, where my responsibilities were develop the requirements that my supervisor, Daniel Zambrano assigned me.
                li.lead
                  | Technologies:
                  .section-tags
                    .box-tag PostgreSQL
                    .box-tag Git
                    .box-tag CSS
                    .box-tag Php
                    .box-tag Slim
                    .box-tag NodeJs
                    .box-tag Ubuntu
                    .box-tag CoffeeScript
                    .box-tag Ruby On Rails
                    .box-tag CodeIgniter

          #experience-4.experience
            .row
              .title.col-lg-6.col-sm-5
                span.position Web Developer
                span.company  – Asociación Civil Casa D’Italia
              .location.col-lg-6.col-sm-5
                img class="location-icon" src="/assets/location.png" alt=""
                span.text Miranda, VE
            .row
              .time.col-lg-6.col-sm-5
                span.text.date Sep. 2013 – Mar. 2014
                span.text.duration (7 months)
              .modality.col-lg-6.col-sm-5
                span.text Modality Remote
            .row
              ul.col-lg-12.list
                li.lead
                  | I developed a system for the association, whose function is to manage the courses they provide. My responsibility was, develop the management system with the required requirements and make system local. It’s an internal system, one is not in the web.
                li.lead
                  | Technologies:
                  .section-tags
                    .box-tag MySQL
                    .box-tag Css
                    .box-tag Javascript
                    .box-tag Php
                    .box-tag HTML
                    .box-tag XAMP
                    .box-tag Windows XP



a name="education"
#education-section
  .container
    .row
      .col-lg-12.col-sm-12
        hr.section-heading-spacer
        .clearfix
        h2.section-heading
          | EDUCATION

        .time-line.col-lg-1.col-sm-1
          span.text Actually
          hr.line-horizontal
          hr.line-vertical
          #circle-1.circle
          #circle-2.circle

        .content.col-lg-11.col-sm-11
          #education-1.education
            .row
              .title.col-lg-6.col-sm-5
                span.position Computing Engineer
                span.company  – I.U.T “Dr. Federico Rivero Palacio”
              .location.col-lg-6.col-sm-5
                img class="location-icon" src="/assets/location.png" alt=""
                span.text Caracas, VE
            .row
              .time.col-lg-6.col-sm-5
                span.text.date (2011 - 2014)
                span.text.duration Honorific Mention: Cum Laude
              .modality.col-lg-6.col-sm-5

          #education-2.education
            .row
              .title.col-lg-6.col-sm-5
                span.position UST in Electricity
                span.company  – I.U.T “Dr. Federico Rivero Palacio”
              .location.col-lg-6.col-sm-5
                img class="location-icon" src="/assets/location.png" alt=""
                span.text Caracas, VE
            .row
              .time.col-lg-6.col-sm-5
                span.text.date (2007 - 2010)
                span.text.duration Mention Telecommunications
              .modality.col-lg-6.col-sm-5




.content-section-b
  .container
    .row
      .col-lg-5.col-lg-offset-1.col-sm-push-6.col-sm-6
        hr.section-heading-spacer
        .clearfix
        h2.section-heading
          | 3D Device Mockups
          br
          | by PSDCovers
        p.lead
          | Turn your 2D designs into high quality, 3D product shots in seconds using free Photoshop actions by 
          a target="_blank" href="http://www.psdcovers.com/" PSDCovers
          | ! Visit their website to download some of their awesome, free photoshop actions!
      .col-lg-5.col-sm-pull-6.col-sm-6
        img class="img-responsive" src="/assets/dog.png" alt=""


.content-section-a
  .container
    .row
      .col-lg-5.col-sm-6
        hr.section-heading-spacer
        .clearfix
        h2.section-heading
          | Google Web Fonts and
          br
          | Font Awesome Icons
        p.lead
          | This template features the 'Lato' font, part of the
          a target="_blank" href="http://www.google.com/fonts" Google Web Font library
          | , as well as 
          a target="_blank" href="http://fontawesome.io" icons from Font Awesome
          | .
      .col-lg-5.col-lg-offset-2.col-sm-6
        img class="img-responsive" src="/assets/phones.png" alt=""



a name="contact"
.banner
  .container
    .row
      .col-lg-6
        h2 Connect to Start Bootstrap:
      .col-lg-6
        ul.list-inline.banner-social-buttons
          li
            a href="https://twitter.com/SBootstrap" class="btn btn-default btn-lg"
              i.fa.fa-twitter.fa-fw
              span.network-name Twitter
          li
            a href="https://github.com/IronSummitMedia/startbootstrap" class="btn btn-default btn-lg"
            i.fa.fa-github.fa-fw
            span.network-name Github
          li
            a href="#" class="btn btn-default btn-lg"
              i.fa.fa-linkedin.fa-fw
              span.network-name Linkedin



footer
  .container
    .row
      .col-lg-12
        ul.list-inline
          li
            a href="#" Home
          li.footer-menu-divider
            | &sdot;
          li
            a href="#about" About
          li.footer-menu-divider
            | &sdot;
          li
            a href="#services" Services
          li.footer-menu-divider
            | &sdot;
          li
            a href="#contact" Contact
        p.copyright.text-muted.small
          | Copyright &copy; Your Company 2014. All Rights Reserved

app/views/knowledges/_form.html.erb
<%= form_for(@knowledge) do |f| %>
  <% if @knowledge.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@knowledge.errors.count, "error") %> prohibited this knowledge from being saved:</h2>

      <ul>
      <% @knowledge.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :type %><br>
    <%= f.text_field :type %>
  </div>
  <div class="field">
    <%= f.label :percentage %><br>
    <%= f.number_field :percentage %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/knowledges/_knowledge.html.erb
<li><%= knowledge.name %></li>

app/views/knowledges/edit.html.erb
<h1>Editing Knowledge</h1>

<%= render 'form' %>

<%= link_to 'Show', @knowledge %> |
<%= link_to 'Back', knowledges_path %>

app/views/knowledges/index.html.erb
<p id="notice"><%= notice %></p>

<%= form_tag knowledges_path, :method => :get, :remote => true do %>
  <div class="search">
    <%= label_tag "search" %><br>
    <%= text_field_tag "search" %>
  </div>
  <div class="actions">
    <%= submit_tag "Search" %>
  </div>
<% end %>


<h1>Listing Knowledges</h1>

<div id="knowledges">
  <%= render @knowledges %>
<br>

<%= link_to 'New Knowledge', new_knowledge_path %>

app/views/knowledges/index.js.erb
$("#knowledges").html("<%= escape_javascript(render(@knowledges)) %>");

app/views/knowledges/new.html.erb
<h1>New Knowledge</h1>

<%= render 'form' %>

<%= link_to 'Back', knowledges_path %>

app/views/knowledges/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @knowledge.name %>
</p>

<p>
  <strong>Type:</strong>
  <%= @knowledge.type %>
</p>

<p>
  <strong>Percentage:</strong>
  <%= @knowledge.percentage %>
</p>

<%= link_to 'Edit', edit_knowledge_path(@knowledge) %> |
<%= link_to 'Back', knowledges_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Portafolio</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js"></script>

</head>
<body>

<%= yield %>

</body>
</html>

app/views/shares/_footer.slim
.container
  p.text-muted.credit
    | Example courtesy

app/views/shares/_header.slim
.navbar-header
  button.navbar-toggle data-target="#bs-example-navbar-collapse-1" data-toggle="collapse" type="button" 
    span.sr-only
    span.icon-bar
    span.icon-bar
    span.icon-bar
  a.navbar-brand href="/" Home
#bs-example-navbar-collapse-1.collapse.navbar-collapse
  ul.nav.navbar-nav
    li class="#{active_section(about_me_path)}"
      = link_to "Acerca de mí", about_me_path
    li class="#{active_section('works')}"
      = link_to "Trabajos", "#"
    li class="dropdown #{active_section('works')}"
      a.dropdown-toggle data-toggle="dropdown" href="#" 
        | Articulos
        b.caret
      ul.dropdown-menu
        li
          a href="#"  Construccion
        li
          a href="#"  Construccion
        li.divider
        li
          a href="#"  Construccion
        li.divider
        li
          a href="#"  Construccion 
    li class="dropdown #{active_section('contact')}"
      = link_to "Contacto", "#"

  ul.nav.navbar-nav.navbar-right
    li
      a href="#"  Comentame